In [4]:
print("hello pytorch")

hello pytorch


In [5]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [6]:
import torch
print(torch.__version__)
from t

2.13.0+cu130


In [7]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
tensor = torch.tensor([1,2])
tensor

tensor([1, 2])

In [9]:
scalar.ndim

0

In [10]:
scalar.item()

7

In [11]:
#Vector

vector = torch.tensor([7,7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
 #MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[0]


tensor([7, 8])

In [17]:
MATRIX[1]

tensor([ 9, 10])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
TENSOR = torch.tensor([
    [[0,1,3],[1,2,4], [5,7,9]]])

TENSOR

tensor([[[0, 1, 3],
         [1, 2, 4],
         [5, 7, 9]]])

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[0, 1, 3],
        [1, 2, 4],
        [5, 7, 9]])

In [22]:
TENSOR[0][0]

tensor([0, 1, 3])

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
ten = torch.tensor([
    [[0,1,3],[1,2,4], [5,7,9]]])

ten

tensor([[[0, 1, 3],
         [1, 2, 4],
         [5, 7, 9]]])

In [25]:
ten[0][0]

tensor([0, 1, 3])

In [33]:
### Random tensors

random_tensor = torch.rand(2,4,3)
random_tensor

tensor([[[0.0421, 0.1333, 0.5222],
         [0.9756, 0.9481, 0.3712],
         [0.1307, 0.6257, 0.7815],
         [0.8645, 0.9128, 0.9393]],

        [[0.0756, 0.2683, 0.4623],
         [0.8403, 0.4280, 0.8760],
         [0.1443, 0.3221, 0.3460],
         [0.5017, 0.3167, 0.2362]]])

In [38]:
# random_image_tensor

random_image_tensor = torch.rand(size = (3, 244,244))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [39]:
random_image_tensor

tensor([[[0.0378, 0.6533, 0.5638,  ..., 0.5243, 0.6422, 0.3552],
         [0.0869, 0.3687, 0.6875,  ..., 0.6229, 0.5030, 0.7694],
         [0.6330, 0.9291, 0.6412,  ..., 0.8042, 0.8733, 0.5788],
         ...,
         [0.4242, 0.2779, 0.5738,  ..., 0.6251, 0.4523, 0.8224],
         [0.8512, 0.8309, 0.5630,  ..., 0.5414, 0.7360, 0.0377],
         [0.8114, 0.9157, 0.8683,  ..., 0.6612, 0.3414, 0.2971]],

        [[0.4723, 0.4287, 0.5922,  ..., 0.7629, 0.8128, 0.4545],
         [0.2793, 0.4643, 0.5494,  ..., 0.0024, 0.4369, 0.0566],
         [0.1054, 0.6637, 0.1764,  ..., 0.3116, 0.8838, 0.6368],
         ...,
         [0.5398, 0.3148, 0.7771,  ..., 0.3679, 0.6227, 0.0213],
         [0.4215, 0.8382, 0.8342,  ..., 0.9107, 0.7425, 0.5040],
         [0.5981, 0.7047, 0.2007,  ..., 0.1804, 0.4158, 0.2504]],

        [[0.5786, 0.1847, 0.3485,  ..., 0.1311, 0.9684, 0.7799],
         [0.1521, 0.4638, 0.4072,  ..., 0.7533, 0.3672, 0.0910],
         [0.1477, 0.3422, 0.2476,  ..., 0.4603, 0.5053, 0.

In [40]:
random_image_tensor.dtype


torch.float32

In [44]:
z = torch.zeros(3,4)

o = torch.ones(3,4)
z, o

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [1]:
# numpy array to tensor

import numpy as np
import torch

In [7]:
np_arr = np.random.rand(2,3)
np_arr

array([[0.58400317, 0.74142225, 0.78915336],
       [0.66582864, 0.78386755, 0.93428183]])

In [9]:
t8 = torch.tensor(np_arr)
t8

tensor([[0.5840, 0.7414, 0.7892],
        [0.6658, 0.7839, 0.9343]], dtype=torch.float64)

In [3]:
t8 = torch.ones(2,3, dtype = int)
t8

tensor([[1, 1, 1],
        [1, 1, 1]])

In [4]:
t9 = torch.rand(2,3)
t9

tensor([[0.9956, 0.7907, 0.0059],
        [0.4426, 0.2080, 0.4359]])

In [5]:
t10 = torch.add(t8, t9)
t10

tensor([[1.9956, 1.7907, 1.0059],
        [1.4426, 1.2080, 1.4359]])

In [12]:
t9.add_(t10)
t9, t9.size()

(tensor([[6.9825, 6.1628, 3.0235],
         [4.7705, 3.8319, 4.7434]]),
 torch.Size([2, 3]))

In [ ]:
t9.reshape(3,2)


## tensor broadcasting
# 1.equal shapes
# 2.one of the dimensions has to be 1

In [16]:
x = torch.empty(5, 4, 3, 1)
x

tensor([[[[9.1828e-33],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
        

In [19]:
y = torch.empty( 1,3,5)
y

tensor([[[1.0855e-32, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [20]:
z = torch.add(x, y)
z

tensor([[[[2.0038e-32, 9.1828e-33, 9.1828e-33, 9.1828e-33, 9.1828e-33],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[1.0855e-32, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[1.0855e-32, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[1.0855e-32, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[1.0855e-32, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e

# vector multiplication

In [21]:
a = torch.tensor([10,20,30,40])

In [23]:
b = torch.tensor([[10], [20], [30], [40]])

In [24]:
c = torch.mul(a, b)

In [25]:
c

tensor([[ 100,  200,  300,  400],
        [ 200,  400,  600,  800],
        [ 300,  600,  900, 1200],
        [ 400,  800, 1200, 1600]])

In [29]:
c.size()
c = torch.randint(0, 20, [2, 10])
c

tensor([[ 2, 11, 12,  8, 14, 18, 15, 12, 13, 13],
        [ 3, 15,  9,  0,  0,  7, 16,  9,  2, 13]])

In [30]:
y = torch.transpose(c, 0, 1)
y

tensor([[ 2,  3],
        [11, 15],
        [12,  9],
        [ 8,  0],
        [14,  0],
        [18,  7],
        [15, 16],
        [12,  9],
        [13,  2],
        [13, 13]])

# Indexing

In [31]:
y[0][0]

tensor(2)

In [32]:
y[0]

tensor([2, 3])

In [33]:
y[-1]

tensor([13, 13])

In [35]:
y[0][1]

tensor(3)

In [36]:
t13 = torch.rand(5,4,7)
t13

tensor([[[0.2108, 0.1455, 0.8472, 0.0318, 0.7462, 0.9337, 0.9075],
         [0.4413, 0.2274, 0.5391, 0.2306, 0.4517, 0.5501, 0.1254],
         [0.0512, 0.3360, 0.9842, 0.3887, 0.2609, 0.3074, 0.8217],
         [0.4303, 0.1295, 0.6147, 0.7021, 0.5400, 0.6304, 0.7623]],

        [[0.7543, 0.9099, 0.9813, 0.3745, 0.9485, 0.7602, 0.0351],
         [0.9132, 0.9383, 0.2711, 0.5468, 0.0023, 0.3830, 0.4058],
         [0.8106, 0.4351, 0.4479, 0.2686, 0.4068, 0.2802, 0.2114],
         [0.2336, 0.2027, 0.7603, 0.8462, 0.6507, 0.6911, 0.5387]],

        [[0.8616, 0.1338, 0.4004, 0.5893, 0.3014, 0.3791, 0.4580],
         [0.5332, 0.7584, 0.4891, 0.2800, 0.2230, 0.6472, 0.5512],
         [0.5783, 0.5915, 0.8954, 0.9029, 0.1728, 0.1171, 0.3759],
         [0.8461, 0.8813, 0.2473, 0.4697, 0.0768, 0.2849, 0.3071]],

        [[0.1030, 0.3017, 0.4871, 0.6720, 0.7193, 0.2073, 0.6216],
         [0.2968, 0.4896, 0.9382, 0.4199, 0.0323, 0.6154, 0.9078],
         [0.2650, 0.1210, 0.7635, 0.6831, 0.5389, 0.7802

In [37]:
t13[0][1]

tensor([0.4413, 0.2274, 0.5391, 0.2306, 0.4517, 0.5501, 0.1254])

In [39]:
t13[0][2][1]

tensor(0.3360)

In [40]:
t13[4][3][-1]

tensor(0.3318)

# Reverse Indexing

In [42]:
t14 = torch.flip(t13, [0, 1])
t14

tensor([[[0.6443, 0.1653, 0.3872, 0.0996, 0.4823, 0.3706, 0.3318],
         [0.9025, 0.9352, 0.6055, 0.0458, 0.7758, 0.8482, 0.5105],
         [0.8760, 0.5672, 0.4599, 0.5420, 0.5236, 0.8316, 0.1431],
         [0.0440, 0.5323, 0.3857, 0.4086, 0.7867, 0.9097, 0.2346]],

        [[0.4502, 0.3958, 0.3359, 0.2808, 0.7519, 0.8334, 0.9725],
         [0.2650, 0.1210, 0.7635, 0.6831, 0.5389, 0.7802, 0.5803],
         [0.2968, 0.4896, 0.9382, 0.4199, 0.0323, 0.6154, 0.9078],
         [0.1030, 0.3017, 0.4871, 0.6720, 0.7193, 0.2073, 0.6216]],

        [[0.8461, 0.8813, 0.2473, 0.4697, 0.0768, 0.2849, 0.3071],
         [0.5783, 0.5915, 0.8954, 0.9029, 0.1728, 0.1171, 0.3759],
         [0.5332, 0.7584, 0.4891, 0.2800, 0.2230, 0.6472, 0.5512],
         [0.8616, 0.1338, 0.4004, 0.5893, 0.3014, 0.3791, 0.4580]],

        [[0.2336, 0.2027, 0.7603, 0.8462, 0.6507, 0.6911, 0.5387],
         [0.8106, 0.4351, 0.4479, 0.2686, 0.4068, 0.2802, 0.2114],
         [0.9132, 0.9383, 0.2711, 0.5468, 0.0023, 0.3830