In [5]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [10]:
class WineDataSet(Dataset):
    def __init__(self):
        #data loading
        xy = np.loadtxt('dataset.csv', delimiter = ",", dtype=np.float32, skiprows = 1)
        x = np.concatenate([xy[0:30, 1:],xy[60:90, 1:],xy[130:150, 1:]])
        y = np.concatenate([xy[0:30, [0]],xy[60:90, [0]],xy[130:150, [0]]])
        x = (x - x.mean(axis=0)) / x.std(axis=0)
        self.x = torch.from_numpy(x).float()
        self.y = torch.from_numpy(y).float() #n_samples, 1
        self.n_samples = x.shape[0]
    def __getitem__(self, index):
        #dataset[0]
        return self.x[index], self.y[index]
    def __len__(self):
        #gives the length of dataset
        return self.n_samples

In [11]:
# using dataset

dataset = WineDataSet()
first_data = dataset[0]
features, lables = first_data
print(features, lables)

tensor([ 1.4133, -0.4102,  0.2263, -0.9990,  1.8413,  0.8140,  1.0631, -0.5787,
         1.3398,  0.5459,  0.0868,  1.7149,  0.8035]) tensor([1.])


In [47]:
# using DataLoader

dataloader = DataLoader(dataset = dataset, batch_size = 1, shuffle= True, num_workers = 0)

dataiter = iter(dataloader)

In [48]:
# checking length
dataset.__len__()

80

In [35]:
dataset[78]

(tensor([ 0.2626,  0.9967,  0.0357,  0.7250, -0.5690, -0.5571, -1.2947,  0.8021,
         -0.4349,  2.2594, -2.1607, -1.3768, -0.4644]),
 tensor([3.]))

In [49]:
# with next function using the iterator

data = next(dataiter)
features, lables = data
print(features, lables)

tensor([[ 0.2373, -0.4010, -0.8788, -0.5899, -0.4313,  0.1836,  0.1712, -0.6599,
         -0.2643, -0.4958, -0.0049,  0.1690,  1.4756]]) tensor([[1.]])


In [50]:
# training loop

num_epochs = 10
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
print(total_samples, n_iterations)


80 20


In [51]:
# dummy training loop

for epoch in range(num_epochs):
    for i , (inputs,labels) in enumerate(dataloader):
        if (i+1)%5 == 0:
            print(f'epoch {epoch+1}/{num_epochs} step{i+1}/{n_iterations} inputs {inputs.shape}')

epoch 1/10 step5/20 inputs torch.Size([1, 13])
epoch 1/10 step10/20 inputs torch.Size([1, 13])
epoch 1/10 step15/20 inputs torch.Size([1, 13])
epoch 1/10 step20/20 inputs torch.Size([1, 13])
epoch 1/10 step25/20 inputs torch.Size([1, 13])
epoch 1/10 step30/20 inputs torch.Size([1, 13])
epoch 1/10 step35/20 inputs torch.Size([1, 13])
epoch 1/10 step40/20 inputs torch.Size([1, 13])
epoch 1/10 step45/20 inputs torch.Size([1, 13])
epoch 1/10 step50/20 inputs torch.Size([1, 13])
epoch 1/10 step55/20 inputs torch.Size([1, 13])
epoch 1/10 step60/20 inputs torch.Size([1, 13])
epoch 1/10 step65/20 inputs torch.Size([1, 13])
epoch 1/10 step70/20 inputs torch.Size([1, 13])
epoch 1/10 step75/20 inputs torch.Size([1, 13])
epoch 1/10 step80/20 inputs torch.Size([1, 13])
epoch 2/10 step5/20 inputs torch.Size([1, 13])
epoch 2/10 step10/20 inputs torch.Size([1, 13])
epoch 2/10 step15/20 inputs torch.Size([1, 13])
epoch 2/10 step20/20 inputs torch.Size([1, 13])
epoch 2/10 step25/20 inputs torch.Size([1,

In [52]:
# linear regression nn 13 inputs 1 output 13 inputs are features, 1 output as labels

class LinearModel(torch.nn.Module):
    def __init__(self):
        super(LinearModel, self).__init__()
        self.linear = torch.nn.Linear(13, 1)
    def forward(self, x):
        return self.linear(x)

In [53]:
model = LinearModel()
loss = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

# linear regression of wine dataset 13 inputs, 1 output

In [54]:
# linear regression training loop

for epoch in range(num_epochs):
    for i , (inputs,labels) in enumerate(dataloader):
        y_hat = model(inputs)
        l = loss(y_hat, labels)
        l.backward()
        optimizer.step()
        optimizer.zero_grad()
        print(f"Epoch [{epoch + 1}/{num_epochs}], Loss: {l.item():.4f}")

Epoch [1/10], Loss: 1.1002
Epoch [1/10], Loss: 18.9569
Epoch [1/10], Loss: 5.9036
Epoch [1/10], Loss: 0.5763
Epoch [1/10], Loss: 13.3797
Epoch [1/10], Loss: 2.6833
Epoch [1/10], Loss: 4.6130
Epoch [1/10], Loss: 4.3273
Epoch [1/10], Loss: 3.4406
Epoch [1/10], Loss: 4.6323
Epoch [1/10], Loss: 3.2515
Epoch [1/10], Loss: 1.2497
Epoch [1/10], Loss: 4.0116
Epoch [1/10], Loss: 1.4023
Epoch [1/10], Loss: 3.3045
Epoch [1/10], Loss: 3.1915
Epoch [1/10], Loss: 4.2249
Epoch [1/10], Loss: 3.1451
Epoch [1/10], Loss: 3.5752
Epoch [1/10], Loss: 5.1878
Epoch [1/10], Loss: 2.8644
Epoch [1/10], Loss: 2.7910
Epoch [1/10], Loss: 1.4978
Epoch [1/10], Loss: 1.3041
Epoch [1/10], Loss: 1.7360
Epoch [1/10], Loss: 0.6015
Epoch [1/10], Loss: 0.0101
Epoch [1/10], Loss: 1.2581
Epoch [1/10], Loss: 3.6983
Epoch [1/10], Loss: 2.7795
Epoch [1/10], Loss: 2.5401
Epoch [1/10], Loss: 1.1637
Epoch [1/10], Loss: 0.8982
Epoch [1/10], Loss: 0.9801
Epoch [1/10], Loss: 0.7774
Epoch [1/10], Loss: 3.3198
Epoch [1/10], Loss: 0.1771

In [55]:
model.eval()

LinearModel(
  (linear): Linear(in_features=13, out_features=1, bias=True)
)

In [56]:
with torch.no_grad():
    prediction = model(dataset.x[0].unsqueeze(0))

print("Actual:", dataset.y[0].item())
print("Predicted:", prediction.item())

Actual: 1.0
Predicted: 0.8290942907333374


In [57]:
# x = xy[0:30, 1:]+xy[60:90, 1:]+xy[130:150, 1:]
#         y = xy[0:30, [0]]+xy[60:90, [0]]+xy[130:150, [0]]

class WineDataSetTesting(Dataset):
    def __init__(self):
        #data loading
        xy = np.loadtxt('dataset.csv', delimiter = ",", dtype=np.float32, skiprows = 1)
        x = np.concatenate([xy[31:61, 1:],xy[91:131, 1:],xy[151:, 1:]])
        y = np.concatenate([xy[31:61, [0]],xy[91:131, [0]],xy[151:, [0]]])
        x = (x - x.mean(axis=0)) / x.std(axis=0)
        self.x = torch.from_numpy(x).float()
        self.y = torch.from_numpy(y).float() #n_samples, 1
        self.n_samples = x.shape[0]
    def __getitem__(self, index):
        #dataset[0]
        return self.x[index], self.y[index]
    def __len__(self):
        #gives the length of dataset
        return self.n_samples

In [58]:
# creating dataloader to the testing_data

testing_dataset = WineDataSetTesting()
dataloader = DataLoader(dataset = testing_dataset, batch_size = 1, shuffle= True, num_workers = 0)

dataiter = iter(dataloader)

In [59]:
# testing each
total = 0
correct = 0
for i , (inputs,labels) in enumerate(dataloader):
    with torch.no_grad():
        prediction = model(dataset.x[0].unsqueeze(0))
        if math.ceil(prediction) == labels:
            correct +=1
        total +=1

print('correctly predicted', correct)
print('total tests', total)



correctly predicted 28
total tests 97
