In [1]:
import torch

In [4]:
x = torch.rand(3, requires_grad = True)
x

tensor([0.8273, 0.1238, 0.1382], requires_grad=True)

In [5]:
# it have gradient function according to operation
y = x*x*2
y

tensor([1.3687, 0.0306, 0.0382], grad_fn=<MulBackward0>)

In [11]:
# example of mean function
z = x.mean()
z

tensor(0.3631, grad_fn=<MeanBackward0>)

In [13]:
# we can able to see the gradient vals 
# how much you need to change the weight
# for forward propagation no need of gradients
print(x.grad)

None


In [14]:
# now one time we go back
z.backward()

In [15]:
# now we can see the gradients
print(x.grad)

tensor([0.3333, 0.3333, 0.3333])


In [16]:
# if output is scalar no need to send the arguments to backward
# if output contain vector then we can send our tensor to backward
z = x**2
v = torch.tensor([0.1,0.01,0.001], dtype=torch.float64)
z.backward(v)
print(x.grad)

tensor([0.4988, 0.3358, 0.3336])


In [ ]:
# by using these we can modify the requries_grad= False in run time
# x.requires_grad_(False)
# x.detach() # it creates a other tensor copy from the original
# with torch.no_grad():
#     pass

# by these we can use the tensor with out the gradient

In [20]:
# a sample script to demonsrate the epochs

weights = torch.ones(4, requires_grad = True)


for epoch in range(2):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [29]:
# with optimizer
# demonstrating how the output changes
weights = torch.ones(4, requires_grad = True)
optimizer = torch.optim.SGD([weights], lr = 0.01)
for epoch in range(5):
    model_output = (weights*3).sum()
    print(model_output)
    model_output.backward()
    print(weights.grad)
    optimizer.step()
    print(weights)
    optimizer.zero_grad()
    

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.9700, 0.9700, 0.9700, 0.9700], requires_grad=True)
tensor(11.6400, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.9400, 0.9400, 0.9400, 0.9400], requires_grad=True)
tensor(11.2800, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.9100, 0.9100, 0.9100, 0.9100], requires_grad=True)
tensor(10.9200, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.8800, 0.8800, 0.8800, 0.8800], requires_grad=True)
tensor(10.5600, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.8500, 0.8500, 0.8500, 0.8500], requires_grad=True)
