In [9]:
import torch
import torch.nn as nn
from termcolor import colored

# design model (input, output size, forwardpass,loss, backward, update weight )

In [22]:
x = torch.tensor([[1],[2],[3],[4]], dtype= torch.float32)
y = torch.tensor([[2],[4],[6],[8]], dtype= torch.float32)

In [27]:
n_samples, n_features = x.shape
print(n_samples, n_features)
x_test = torch.tensor([5], dtype= torch.float32)
input_size, output_size = n_features, n_features
model = nn.Linear(input_size, output_size)
# w = torch.tensor(0.0, dtype=torch.float32, requires_grad = True)

4 1


In [30]:
print(f'preciction before training:f(5) = {model(x_test).item():.3f}')

learning_rate = 0.01
n_iters = 100
# loss
# no need manually
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)


for epoch in range(n_iters):
    y_pred = model(x)
    l = loss(y, y_pred)
    
    print(colored(f'epoch {epoch}', "red"))
    print(colored(f'loss {l}', "green"))
    l.backward()
    optimizer.step()
    [w, b] = model.parameters()
    print(colored(f'gradients after backward {w, b}', "blue"))
    optimizer.zero_grad()
    print(colored(f'updated weights  {w}', "yellow"))

print(f'preciction after training:f(5) = {model(x_test).item():.3f}')
    

preciction before training:f(5) = 2.328
epoch 0
loss 19.826374053955078
gradients after backward (Parameter containing:
tensor([[0.8417]], requires_grad=True), Parameter containing:
tensor([-0.5802], requires_grad=True))
updated weights  Parameter containing:
tensor([[0.8417]], requires_grad=True)
epoch 1
loss 13.758508682250977
gradients after backward (Parameter containing:
tensor([[1.0445]], requires_grad=True), Parameter containing:
tensor([-0.5106], requires_grad=True))
updated weights  Parameter containing:
tensor([[1.0445]], requires_grad=True)
epoch 2
loss 9.548133850097656
gradients after backward (Parameter containing:
tensor([[1.2133]], requires_grad=True), Parameter containing:
tensor([-0.4526], requires_grad=True))
updated weights  Parameter containing:
tensor([[1.2133]], requires_grad=True)
epoch 3
loss 6.626636981964111
gradients after backward (Parameter containing:
tensor([[1.3540]], requires_grad=True), Parameter containing:
tensor([-0.4043], requires_grad=True))
upda