In [3]:
import torch
import torchvision
import numpy as np
from torch.utils.data import Dataset

In [26]:
class WineDataset(Dataset):
    def __init__(self, transform = None):
        xy = np.loadtxt("./dataset.csv", delimiter=',', dtype= np.float32, skiprows=1)
        self.n_samples = xy.shape[0]

        self.x = xy[:, 1:]
        self.y = xy[:, [0]]
        self.transform = transform

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample

    def __len(self):
        return self.n_samples

In [30]:
# own transform class

class ToTensor:
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [32]:
# multiplicative transform the data
class MulTransform:
    def __init__(self, factor):
        self.factor = factor
    def __call__(self, sample):
        i, o = sample
        i = i* self.factor
        return i, o

In [10]:
dataset = WineDataset(transform = ToTensor())
# now it will become tensor

In [11]:
first_data = dataset[0]
first_data

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [12]:
features, labels = first_data
print(features, labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [13]:
# it is normal numpy array

ds = WineDataset()
ds[0]

(array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03], dtype=float32),
 array([1.], dtype=float32))

In [33]:
# now using multransorm
composed = torchvision.transforms.Compose([ToTensor(), MulTransform(3)])
dataset = WineDataset(transform=composed)
first_data = dataset[0]
features, labels = first_data
print(features)
print(labels)

tensor([4.2690e+01, 5.1300e+00, 7.2900e+00, 4.6800e+01, 3.8100e+02, 8.4000e+00,
        9.1800e+00, 8.4000e-01, 6.8700e+00, 1.6920e+01, 3.1200e+00, 1.1760e+01,
        3.1950e+03])
tensor([1.])
